### ISSUE TITLE
Dashboards are lost on server reboot sometimes

### ISSUE THREAD

**Issue by samuelengineer** [canonical/grafana-k8s-operator#273] opened 2023-11-06 04:18 UTC
### Bug Description

Sometimes when there is a reboot, the dashboards disappear from grafana.  Even though the dashboards' data is still visible in the unit relation data.

I haven't been able to reliably reproduce the issue yet, but this bug report is a start in case others have seen this too.

### To Reproduce

see above

### Environment

see above

### Relevant log output

```shell
N/A
```

**Comment by lucabello** [comment] 2023-12-07 14:22
On our side it seems like it should be smooth because grafana [uses controller storage](https://github.com/canonical/grafana-k8s-operator/blob/1ac90904af72fb1ee55602447024d99ba0237613/src/charm.py#L1381)

I will close the issue due to lack of reproducibility, but we'll keep an eye on it!

**Closed by lucabello** 2023-12-07 14:22 UTC
Labels: Type: Bug, Status: Triage
