### ISSUE TITLE
error status on config-changed

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/grafana-k8s-operator#212] opened 2023-04-19 07:38 UTC
### Bug Description

grafana raises an uncaught exception during config-changed while cos-lite has just been deployed and is settling

### To Reproduce

1. `juju deploy cos-lite --trust --channel=edge`
2. `juju config traefik external_hostname=foo.com`
3. `juju run-action grafana/0 get-admin-password --wait`

step 3 returns with:
```
❯ j run-action grafana/0 get-admin-password --wait                         
unit-grafana-0:                                                            
  UnitId: grafana/0                                                        
  id: "4"                                                                  
  message: Grafana is not reachable yet. Please try again in a few minutes 
  results: {}                                                              
  status: failed                                                           
  timing:                                                                  
    completed: 2023-04-19 07:10:13 +0000 UTC                               
    enqueued: 2023-04-19 07:09:43 +0000 UTC                                
    started: 2023-04-19 07:10:11 +0000 UTC                                 
```                                              

### Environment

```
❯ jhack jenv                                   
                juju info v0.1                  
┌────────────┬────────────────────────────────┐ 
│ jhack      │ 0.3.15                         │ 
│ juju       │ 2.9.42-ubuntu-amd64            │ 
│ microk8s   │ MicroK8s v1.26.3 revision 4959 │ 
│ lxd        │ 5.0.2                          │ 
│ multipass  │ 1.11.0                         │ 
│ multipassd │ 1.11.0                         │ 
│ os         │ Ubuntu 22.04.2 LTS             │ 
│ kernel     │ Linux 5.19.0-38-generic x86_64 │ 
└────────────┴────────────────────────────────┘ 
```

### Relevant log output

```shell
unit-grafana-0: 09:09:37 INFO unit.grafana/0.juju-log Restarted replication                                              
unit-loki-0: 09:09:37 INFO juju.worker.uniter.operation ran "ingress-relation-created" hook (via hook dispatching script:
dispatch)                                                                                                                
unit-grafana-0: 09:09:37 INFO unit.grafana/0.juju-log Kubernetes resources for app 'grafana', container 'grafana' patched
successfully: ResourceRequirements(claims=None, limits={}, requests={'cpu': '0.25', 'memory': '200Mi'})                  
unit-loki-0: 09:09:37 INFO juju.worker.uniter found queued "leader-elected" hook                                         
unit-grafana-0: 09:09:37 ERROR unit.grafana/0.juju-log Uncaught exception while in charm code:                           
Traceback (most recent call last):                                                                                       
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open                                                     
    h.request(req.get_method(), req.selector, req.data, headers,                                                         
  File "/usr/lib/python3.8/http/client.py", line 1256, in request                                                        
    self._send_request(method, url, body, headers, encode_chunked)                                                       
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request                                                  
    self.endheaders(body, encode_chunked=encode_chunked)                                                                 
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders                                                     
    self._send_output(message_body, encode_chunked=encode_chunked)                                                       
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output                                                   
    self.send(msg)                                                                                                       
  File "/usr/lib/python3.8/http/client.py", line 951, in send                                                            
    self.connect()                                                                                                       
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 252, in connect                              
    self.sock.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1486, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 266, in http_open
    return self.do_open(_UnixSocketConnection, req,  # type:ignore
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 1172, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 820, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 895, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 273, in _configure_ingress
    self._configure()
  File "./src/charm.py", line 409, in _configure
    if self.containers["workload"].get_plan().services != self._build_layer().services:
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/model.py", line 1873, in get_plan
    return self._pebble.get_plan()
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1774, in get_plan
    resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1453, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1499, in _request_raw
    raise ConnectionError(e.reason)
ops.pebble.ConnectionError: [Errno 2] No such file or directory
unit-grafana-0: 09:09:37 INFO juju.worker.caasunitterminationworker terminating due to SIGTERM
unit-grafana-0: 09:09:37 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch)
failed: signal: terminated
```

### Additional context

error resolved itself after a couple of retries

**Comment by Abuelodelanada** [comment] 2023-11-21 18:10
Deploying these edge versions:

```shell
╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ jst           
Model  Controller  Cloud/Region        Version  SLA          Timestamp
cos    microk8s    microk8s/localhost  3.1.6    unsupported  15:07:56-03:00

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  edge      96  10.152.183.145  no       
catalogue              active      1  catalogue-k8s     edge      31  10.152.183.192  no       
grafana       9.2.1    active      1  grafana-k8s       edge      93  10.152.183.81   no       
loki          2.7.4    active      1  loki-k8s          edge     104  10.152.183.223  no       
prometheus    2.47.2   active      1  prometheus-k8s    edge     156  10.152.183.146  no       
traefik       2.10.4   active      1  traefik-k8s       edge     164  192.168.1.250   no       

Unit             Workload  Agent  Address      Ports  Message
alertmanager/0*  active    idle   10.1.38.122         
catalogue/0*     active    idle   10.1.38.84          
grafana/0*       active    idle   10.1.38.113         
loki/0*          active    idle   10.1.38.111         
prometheus/0*    active    idle   10.1.38.94          
traefik/0*       active    idle   10.1.38.124         
```

In these environment:

```shell
╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ juju --version                                                                                                                      
3.1.6-genericlinux-amd64


╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ microk8s version                                                                                                                     
MicroK8s v1.27.7 revision 6101
```

Produces no errors:

```shell
╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ juju run grafana/0 get-admin-password                                                                                                
Running operation 1 with 1 task
  - task 2 on unit-grafana-0

Waiting for task 2...
admin-password: QHL9QN4s132f
url: http://foo.com/cos-grafana
```

I'll manually test it in juju 2.9.x.

**Comment by Abuelodelanada** [comment] 2023-11-22 13:49
Closing this issue since it is not possible to reproduce it now.

**Closed by Abuelodelanada** 2023-11-22 13:49 UTC
Labels: Type: Bug, Status: Triage
